# additional data require to create the Docker image
packaging:
  # files to add to the build, usually used with ADD in the Dockerfile
  add:
    # the plugin always filters
    - target/${project.artifactId}-${project.version}-fat.jar
# optional list of port to expose on the host
ports:
  - 80

tag: zanox/${project.artifactId}:${project.version}
